# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

python:
  version: 3.7
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

formats:
  - pdf
