# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# We need to build sktime before building the docs because otherwise Sphinx
#  cannot read the docstrings from Cython and C extension files
python:
  version: 3.7
  install:
    # install build requirements
    - requirements: build_tools/requirements.txt
    # build sktime using `python ./setup.py install --force`
    - method: setuptools
      path: .
    # install doc requirements
    - requirements: docs/requirements.txt
    # Install pytorch and signatory for the signatures module.
    # Note: torch must be installed via conda for appveyor and signatory must be
    # installed after pytorch.
    - cmd: conda install pytorch=1.5.0 cpuonly -c pytorch
    - cmd: pip install signatory==1.2.1.1.5.0 --no-cache-dir --force-reinstall

sphinx:
  configuration: docs/source/conf.py
