# author: Markus Löning
#
# adapted from
# - https://iscinumpy.gitlab.io/post/azure-devops-python-wheels/
# - https://iscinumpy.gitlab.io/post/azure-devops-releases/

variables:
  REQUIREMENTS: build_tools/requirements.txt
<<<<<<< HEAD
  EXCLUDE_PYTHON_VERSIONS: "2.7, 3.5"  # comma-separate string
=======
  EXCLUDE_PYTHON_VERSIONS: "2.7, 3.5, 3.9"  # comma-separate string
>>>>>>> 67c56be8b1e838f2628df829946f795b7dba9aed

trigger:
  branches:
    include:
      - master
      - dev
  tags:
    include:
      - '*'
pr:
  # Cancel if new commits are pushed to the same PR
  autoCancel: true

stages:
  - stage: 'Linting'
    jobs:
      - job: 'Linting'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: UsePythonVersion@0
            displayName: 'Use Python version'
            inputs:
              versionSpec: 3.x
          - script: pip install flake8
            displayName: 'Installing flake8'
          - task: Bash@3
            displayName: 'Linting'
            inputs:
              filePath: maint_tools/linting.sh

  - stage: 'Build'
    dependsOn: 'Linting'
    condition: succeeded('Linting')
    jobs:
      - job: 'manylinux'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - template: build_tools/azure/build_manylinux_wheels.yml
          - template: build_tools/azure/publish.yml
        strategy:
          matrix:
            64x2010:  # 64 bit 2010
              PLATFORM: manylinux2010_x86_64
              IMAGE: quay.io/pypa/manylinux2010_x86_64
              PYTHON_ARCHITECTURE: x64
            64x:  # 64 bit
              PLATFORM: manylinux1_x86_64
              IMAGE: quay.io/pypa/manylinux1_x86_64
              PYTHON_ARCHITECTURE: x64
            #            86x:  # 32 bit
            #              PLATFORM: manylinux1_i686
            #              IMAGE: quay.io/pypa/manylinux1_i686
            #              PYTHON_ARCHITECTURE: x86
            64x2014:  # 64 bit
              PLATFORM: manylinux2014_x86_64
              IMAGE: quay.io/pypa/manylinux2014_x86_64
              PYTHON_ARCHITECTURE: x86

  - stage: 'Deploy'
    dependsOn: 'Build'
<<<<<<< HEAD
    condition: and(succeeded('Build'), eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
=======
    condition: and(succeeded('Build'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
>>>>>>> 67c56be8b1e838f2628df829946f795b7dba9aed
    jobs:
      - job: 'deploy_to_pypi'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Collect wheels'
            inputs:
<<<<<<< HEAD
              source: 'specific'
              project: 'sktime'
              pipeline: 'alan-turing-institute.sktime'
              runVersion: 'latestFromBranch'
              runBranch: 'refs/heads/master'
              tags: '^v[0-9]\.[0-9]\.[0-9]$'
=======
              source: 'current'
              tags: '^v[0-9]+\.[0-9]+\.[0-9]+'
>>>>>>> 67c56be8b1e838f2628df829946f795b7dba9aed
              patterns: 'wheels_*/*manylinux*.whl'
              path: 'download/'
          - script: |
              mkdir dist
              cp download/wheels_*/*manylinux*.whl dist/
              ls -lh dist/
            displayName: 'Select and list wheels'
<<<<<<< HEAD
=======
          - task: UsePythonVersion@0
            displayName: 'Use Python version'
            inputs:
              versionSpec: 3.x
>>>>>>> 67c56be8b1e838f2628df829946f795b7dba9aed
          - script: |
              pip install --upgrade twine
            displayName: 'Install twine'
          - task: TwineAuthenticate@1
            displayName: 'Twine Authenticate'
            inputs:
              # configured in https://dev.azure.com/<user>/<project>/_settings/adminservices
              pythonUploadServiceConnection: PyPI
          - script: |
<<<<<<< HEAD
              ls -lh dist/*.whl
            # twine upload -r pypi --config-file $(PYPIRC_PATH) --skip-existing --verbose dist/*.whl
=======
              python -m twine upload -r pypi --config-file $(PYPIRC_PATH) --non-interactive --skip-existing --verbose dist/*.whl
>>>>>>> 67c56be8b1e838f2628df829946f795b7dba9aed
            displayName: 'Upload wheels to PyPI'
