name: upload-to-pypi

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest ]
        python-version: [ 3.6.8, 3.7.9, 3.8.8 ]
    steps:
      - uses: actions/checkout@v2
      - name: Get Python
        run: curl https://www.python.org/ftp/python/${{matrix.python-version}}/python-${{matrix.python-version}}-macosx10.9.pkg -o "python.pkg"
      - name: Install Python
        run: sudo installer -pkg python.pkg -target /
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install OS packages
        run: brew install libomp
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build_tools/requirements.txt
      - name: Build wheel
        run: |
          export CC=/usr/bin/clang
          export CXX=/usr/bin/clang++
          export CPPFLAGS="$CPPFLAGS -Xpreprocessor -fopenmp"
          export CFLAGS="$CFLAGS -I/usr/local/opt/libomp/include"
          export CXXFLAGS="$CXXFLAGS -I/usr/local/opt/libomp/include"
          export LDFLAGS="$LDFLAGS -L/usr/local/opt/libomp/lib -lomp"
          export DYLD_LIBRARY_PATH=/usr/local/opt/libomp/lib
          export PATH="/usr/local/opt/ccache/libexec:$PATH"
          python setup.py sdist bdist_wheel
      - name: Install from wheel
        run: pip install --pre --no-index --no-deps --find-links dist/ sktime
      - name: Run tests
        run: |
          mkdir -p testdir/
          cp .coveragerc testdir/
          cp setup.cfg testdir/
          cd testdir/
          pytest --showlocals --durations=10 --pyargs --cov-report=xml --cov=sktime sktime
      - name: Upload wheel and source tarball to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          ls -l dist/*
          python -m pip install --upgrade twine
          python -m twine upload -r pypi --non-interactive --skip-existing --verbose dist/*
